### ISSUE TITLE
Error during mvnw clean install 

### ISSUE THREAD

**Issue by jeevitesh** [mbhave/release-notes-generator#12]
Hi,
I clone the project added some basic details in the application.yaml file like
releasenotes.github:
    organization: 
    name: *******
    username: *****
    password: ******
Then ran the command mvnw clean install getting below error, Please help me to resolve the issue.
  <testcase name="generateWhenNoEnhancements" classname="io.spring.releasenotesgenerator.ChangelogGeneratorTests" time="0.009">
    <failure message="expected:&lt;...# :beetle: Bug fixes[&#10;&#10;- Bug 1 [#1](bug-1-url)&#10;- Bug 3 [#3](bug-3-url)&#10;&#10;## :heart: Contributors&#10;&#10;Weâ€™d like to thank all the contributors who worked on our current release!&#10;&#13;]&#10;- [@contributor1](c...&gt; but was:&lt;...# :beetle: Bug fixes[&#10;&#10;- Bug 1 [#1](bug-1-url)&#10;- Bug 3 [#3](bug-3-url)&#10;&#10;## :heart: Contributors&#10;&#10;We’d like to thank all the contributors who worked on our current release!&#10;]&#10;- [@contributor1](c...&gt;" type="org.junit.ComparisonFailure"><![CDATA[org.junit.ComparisonFailure: 
expected:<...# :beetle: Bug fixes[

- Bug 1 [#1](bug-1-url)
- Bug 3 [#3](bug-3-url)

## :heart: Contributors

Weâ€™d like to thank all the contributors who worked on our current release!

]
- [@contributor1](c...> but was:<...# :beetle: Bug fixes[

- Bug 1 [#1](bug-1-url)
- Bug 3 [#3](bug-3-url)

## :heart: Contributors

We’d like to thank all the contributors who worked on our current release!
]
- [@contributor1](c...>
	at io.spring.releasenotesgenerator.ChangelogGeneratorTests.assertOutputisCorrect(ChangelogGeneratorTests.java:135)
	at io.spring.releasenotesgenerator.ChangelogGeneratorTests.generateWhenNoEnhancements(ChangelogGeneratorTests.java:86)
]]></failure>
  </testcase>
  <testcase name="generateWhenDuplicateContributor" classname="io.spring.releasenotesgenerator.ChangelogGeneratorTests" time="0.008">
    <failure message="expected:&lt;... :star: New Features[&#10;&#10;- Enhancement 1 [#2](enhancement-1-url)&#10;- Enhancement 2 [#4](enhancement-2-url)&#10;- Enhancement 3 [#5](enhancement-5-url)&#10;- Enhancement 4 [#6](enhancement-6-url)&#10;&#10;## :heart: Contributors&#10;&#10;Weâ€™d like to thank all the contributors who worked on our current release!&#10;&#13;]&#10;- [@contributor1](c...&gt; but was:&lt;... :star: New Features[&#10;&#10;- Enhancement 1 [#2](enhancement-1-url)&#10;- Enhancement 2 [#4](enhancement-2-url)&#10;- Enhancement 3 [#5](enhancement-5-url)&#10;- Enhancement 4 [#6](enhancement-6-url)&#10;&#10;## :heart: Contributors&#10;&#10;We’d like to thank all the contributors who worked on our current release!&#10;]&#10;- [@contributor1](c...&gt;" type="org.junit.ComparisonFailure"><![CDATA[org.junit.ComparisonFailure: 
expected:<... :star: New Features[

- Enhancement 1 [#2](enhancement-1-url)
- Enhancement 2 [#4](enhancement-2-url)
- Enhancement 3 [#5](enhancement-5-url)
- Enhancement 4 [#6](enhancement-6-url)

## :heart: Contributors

Weâ€™d like to thank all the contributors who worked on our current release!

]
- [@contributor1](c...> but was:<... :star: New Features[

- Enhancement 1 [#2](enhancement-1-url)
- Enhancement 2 [#4](enhancement-2-url)
- Enhancement 3 [#5](enhancement-5-url)
- Enhancement 4 [#6](enhancement-6-url)

## :heart: Contributors

We’d like to thank all the contributors who worked on our current release!
]
- [@contributor1](c...>
	at io.spring.releasenotesgenerator.ChangelogGeneratorTests.assertOutputisCorrect(ChangelogGeneratorTests.java:135)
	at io.spring.releasenotesgenerator.ChangelogGeneratorTests.generateWhenDuplicateContributor(ChangelogGeneratorTests.java:126)
]]></failure>
  </testcase>
</testsuite>

**Comment by snicoll** [comment]
@jeevitesh the release notes generated has moved to `spring-io`, see https://github.com/spring-io/github-changelog-generator
